name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe the bug or unexpected behavior you encountered.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue.
      placeholder: |
        1. Run command '...'
        2. Open viewer at '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what you observed
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details.
      value: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Bun version: [output of `bun --version`]
        - Claude Code version: [e.g., 1.0.0]
        - Browser (for viewer issues): [e.g., Chrome 120]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: (Optional) Do you have ideas on how to fix this?
      placeholder: Your suggestions for fixing the bug
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, error messages, or screenshots.
      placeholder: Error messages, logs, screenshots, etc.
    validations:
      required: false
